### ISSUE TITLE
Call to a member function render() on null

### ISSUE THREAD

**Issue by ronniebrito** [Daniel-KM/Omeka-S-module-Thesaurus#1]
Hi, 

This error is occuring when showing a thesaurus using tree structure in a omeka s webpage. 

is data misconfigured? 

Error
Call to a member function render() on null

Detalhes:

Error: Call to a member function render() on null in /var/www/omeka/modules/Thesaurus/view/common/thesaurus-tree-recursive.phtml:13
Stack trace:
#0 /var/www/omeka/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include()
#1 /var/www/omeka/vendor/zendframework/zend-view/src/Helper/Partial.php(62): Zend\View\Renderer\PhpRenderer->render()
#2 [internal function]: Zend\View\Helper\Partial->__invoke()

**Comment by Daniel-KM** [comment]
This is fixed in the new version 3.0.4.
