### ISSUE TITLE
Thesaurus 3.4.11 wont install method installDir() not found

### ISSUE THREAD

**Issue by PomadaGH** [Daniel-KM/Omeka-S-module-Thesaurus#2]
Hi,
when trying to install I get the error:
Error: Call to undefined method Thesaurus\Module::installDir() in ..../modules/Thesaurus/Module.php:73

Indeed I can nowhere find this method. Where should it be defined? What should it do? Can I just remove it?

Greetings John

**Comment by Daniel-KM** [comment]
Fixed in 3.4.12.
